name: Build and publish backend docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: twihno
        password: ${{ GITHUB_TOKEN }}

    - name: Build and push to Docker registries
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        platforms: linux/amd64,linux/arm64/v8
        file: ./Dockerfile
        push: true
        tags: |
          twihno/abfahrten-backend:latest
          ghcr.io/twihno/abfahrten-backend:latest

