name: Build and publish backend docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Docker registries
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            twihno/abfahrten-backend:latest
            ghcr.io/twihno/abfahrten-backend:latest
